// is auto-generated at build-time
package version

// Default build-time variable for lib-import.
// This file is overridden on build with build-time informations.
const (
	GitCommit          string = "6f2fbf076c75759e5499d19bbe08e29ce84aa3e1"
	GitBranch          string = "feature-status-resolver"
	GitTag             string = "v1.0.0"
	BuildTime          string = "Mo 30. Nov 17:55:58 CET 2020"
)

// AUTOGENERATED FILE; see internal/framework/version/version.go
