// is auto-generated at build-time
package version

// Default build-time variable for lib-import.
// This file is overridden on build with build-time informations.
const (
	GitCommit          string = "cb6fd470f8950831ef3b0abc22a730df300002de"
	GitBranch          string = "feature-support-optional-enum-parameters"
	GitTag             string = "v4.4.2"
	BuildTime          string = "Mon  9 Mar 2020 10:36:14 CET"
)

// AUTOGENERATED FILE; see internal/framework/version/version.go
