// is auto-generated at build-time
package version

// Default build-time variable for lib-import.
// This file is overridden on build with build-time informations.
const (
	GitCommit          string = "5b34a96f8b49900991a9ffea5116e90c7efba004"
	GitBranch          string = "fix-parameter-required-else-block"
	GitTag             string = "v1.0.0"
	BuildTime          string = "Sa 12. Dez 13:07:22 CET 2020"
)

// AUTOGENERATED FILE; see internal/framework/version/version.go
