// this file is not autogenerated

package api

import (
	"log"
	"net/http"
)

type BadRequestHTTPTransport struct {
	http.Transport
	Code string
}

func (lt *BadRequestHTTPTransport) RoundTrip(req *http.Request) (resp *http.Response, err error) {
	resp, err = lt.Transport.RoundTrip(req)
	if err != nil {
		return nil, err
	}
	if resp.StatusCode != 400 {
		log.Fatalf("Http transport: status code isn't ok, should be bad request (%d, %d)", resp.StatusCode, 400)
	}
	return
}
